# Configuration for Docker Compose local testing
databases:
  - name: "source-db"
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "postgres"
    dbname: "testdb"
    role: "source"
    
  - name: "target-db"
    host: "localhost"
    port: 5433
    user: "postgres"
    password: "postgres"
    dbname: "testdb"
    role: "target"

server:
  port: 8080
  refresh_interval: 5

monitoring:
  lag_threshold: 1048576  # 1MB
  inactive_threshold: 60
